
#
# These sources are part of the "PyThon Programming Series" by Edgar Milvus, 
# you can find it on Amazon: https://www.amazon.com/dp/B0FTTQNXKG or
# https://tinyurl.com/PythonProgrammingSeries 
# New books info: https://linktr.ee/edgarmilvus 
#
# MIT License
# Copyright (c) 2025 Edgar Milvus
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# Source File: basic_basic_code_example.py
# Description: Basic Code Example
# ==========================================

import os
from flask import Flask, render_template_string, render_template

# --- 1. Define the content of the Static File (CSS) ---

# This string represents the content of static/css/style.css
STYLE_CSS = """
/* Set a consistent font and background for the entire page */
body {
    font-family: 'Arial', sans-serif;
    background-color: #f0f0f5; /* Light lavender background */
    color: #333; /* Dark gray text */
    margin: 0;
    padding: 20px;
    text-align: center; /* Center all block content */
}

/* Style the main heading */
h1 {
    color: #0056b3; /* Deep blue color */
    border-bottom: 2px solid #0056b3;
    padding-bottom: 10px;
    display: inline-block;
}

/* Style the paragraph text */
p {
    font-size: 1.2em;
    line-height: 1.6;
}
"""

# --- 2. Define the content of the Template File (HTML) ---

# This string represents the content of templates/index.html
# CRITICAL: Note the use of url_for() to link the static asset.
INDEX_HTML = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Flask Static Demo</title>
    <!-- 
        CRITICAL LINE: Linking the CSS file.
        Flask uses url_for('static', filename='...') to generate the correct URL.
    -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
</head>
<body>
    <h1>Welcome to the Static File Server!</h1>
    <p>
        If this text is deep blue and the background is light lavender, 
        the static file (style.css) was served successfully.
    </p>
    <p>
        The URL for the stylesheet was dynamically generated by Flask.
    </p>
</body>
</html>
"""

# --- 3. Setup and Initialization ---

app = Flask(__name__)

# Helper function to ensure necessary files are created for this demonstration
def setup_files():
    """Creates the necessary directory structure and files if they don't exist."""
    
    # Define paths relative to the current script execution location
    template_dir = os.path.join(os.getcwd(), 'templates')
    static_dir = os.path.join(os.getcwd(), 'static')
    css_dir = os.path.join(static_dir, 'css')
    
    # Ensure directories exist
    os.makedirs(template_dir, exist_ok=True)
    os.makedirs(css_dir, exist_ok=True)
    
    # Write the HTML template file
    with open(os.path.join(template_dir, 'index.html'), 'w') as f:
        f.write(INDEX_HTML)
        print("Created templates/index.html")

    # Write the CSS static file
    with open(os.path.join(css_dir, 'style.css'), 'w') as f:
        f.write(STYLE_CSS)
        print("Created static/css/style.css")

# Execute file setup before running the app
setup_files()


# --- 4. Define the Route ---

@app.route('/')
def index():
    # Flask automatically looks for index.html inside the 'templates' folder
    return render_template('index.html')


# --- 5. Run the Application ---

if __name__ == '__main__':
    # Setting debug=True allows automatic reloading and better error messages
    print("\nApplication ready. Access at http://127.0.0.1:5000/")
    app.run(debug=True)
