
#
# These sources are part of the "PyThon Programming Series" by Edgar Milvus, 
# you can find it on Amazon: https://www.amazon.com/dp/B0FTTQNXKG or
# https://tinyurl.com/PythonProgrammingSeries 
# New books info: https://linktr.ee/edgarmilvus 
#
# MIT License
# Copyright (c) 2025 Edgar Milvus
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# Source File: project_advanced_application_script.py
# Description: Advanced Application Script
# ==========================================

import sys
from collections import defaultdict
from typing import List, Tuple, Dict, Any

# --- 1. CONFIGURATION AND DATA SETUP ---

# Define the target parameters for filtering
TARGET_CATEGORY = 'Electronics'
TARGET_STATUS = 'Completed'

# Raw sales data structure:
# (ID, Region, Category, Quantity, Unit_Price, Status)
RawTransaction = Tuple[int, str, str, int, float, str]
RAW_SALES_DATA: List[RawTransaction] = [
    (1001, 'North', 'Electronics', 5, 120.50, 'Completed'),
    (1002, 'South', 'Apparel', 10, 25.00, 'Completed'),
    (1003, 'West', 'Electronics', 2, 450.00, 'Completed'),
    (1004, 'East', 'Home Goods', 1, 75.99, 'Completed'),
    (1005, 'North', 'Electronics', 1, 999.99, 'Returned'),
    (1006, 'South', 'Electronics', 3, 300.00, 'Completed'),
    (1007, 'West', 'Apparel', 5, 50.00, 'Completed'),
    (1008, 'East', 'Electronics', 4, 150.00, 'Completed'),
    (1009, 'North', 'Electronics', 10, 50.00, 'Completed'),
    (1010, 'South', 'Electronics', 1, 1200.00, 'Pending'),
    (1011, 'West', 'Electronics', 7, 10.00, 'Completed'),
    (1012, 'North', 'Home Goods', 2, 250.00, 'Completed'),
    (1013, 'East', 'Electronics', 2, 800.00, 'Completed'),
    (1014, 'West', 'Electronics', 3, 220.00, 'Cancelled'),
]

# --- 2. CORE PROCESSING FUNCTIONS ---

def display_summary(title: str, data: Dict[str, float]) -> None:
    """Prints the final aggregated results in a readable format."""
    print("-" * 50)
    print(f"{title}:")
    print("-" * 50)
    
    # Simple list comprehension for formatted output strings
    output_lines = [
        f"| {region:<10} | ${revenue:,.2f} |" 
        for region, revenue in sorted(data.items())
    ]
    
    print("\n".join(output_lines))
    print("-" * 50)


def analyze_regional_revenue(data: List[RawTransaction]) -> Dict[str, float]:
    """
    Filters raw data, calculates revenue, and aggregates results by region 
    using List Comprehensions and defaultdict.
    """
    
    # 2.1. Conditional List Comprehension for Filtering and Transformation
    # We filter transactions based on two criteria (Category AND Status)
    # and simultaneously transform the data into (Region, Calculated Revenue).
    # Indices: (0=ID, 1=Region, 2=Category, 3=Qty, 4=Price, 5=Status)
    filtered_revenue_data: List[Tuple[str, float]] = [
        (transaction[1], transaction[3] * transaction[4])
        for transaction in data
        if transaction[2] == TARGET_CATEGORY 
        if transaction[5] == TARGET_STATUS
    ]
    
    print(f"Total filtered 'Electronics' transactions: {len(filtered_revenue_data)}")
    
    # 2.2. Aggregation Setup (Using defaultdict)
    # We initialize a defaultdict where the default factory is 'float' (0.0).
    regional_totals: Dict[str, float] = defaultdict(float)
    
    # 2.3. Processing Aggregation
    # We iterate over the concise, pre-processed list generated by the LC.
    for region, revenue in filtered_revenue_data:
        regional_totals[region] += revenue
        
    # 2.4. Final Output Transformation (List Comprehension for high-value regions)
    
    # Define a high-value threshold
    HIGH_VALUE_THRESHOLD = 1500.00
    
    # Use a list comprehension to identify regions exceeding the threshold
    high_value_regions: List[str] = [
        region 
        for region, total in regional_totals.items()
        if total >= HIGH_VALUE_THRESHOLD
    ]
    
    print(f"\nRegions exceeding ${HIGH_VALUE_THRESHOLD:,.2f} in revenue: {high_value_regions}")
    
    # We return the standard dict representation for final display
    return dict(regional_totals)


# --- 3. EXECUTION ---

if __name__ == "__main__":
    print("--- Pythonic Sales Data Analyzer ---")
    
    # Execute the primary analysis function
    final_results = analyze_regional_revenue(RAW_SALES_DATA)
    
    # Display the structured summary
    display_summary("Aggregated Electronics Revenue by Region", final_results)

    # Example of a nested list comprehension:
    # If we wanted to see all individual revenue items categorized by North/South
    
    NORTH_SOUTH_REVENUES = [
        (region, revenue)
        for region, revenue in [
            (t[1], t[3] * t[4])
            for t in RAW_SALES_DATA
            if t[2] == TARGET_CATEGORY and t[5] == TARGET_STATUS
        ]
        if region in ('North', 'South')
    ]
    
    print("\n--- Nested LC Example: North/South Revenue Items ---")
    print(f"Individual North/South Revenues: {NORTH_SOUTH_REVENUES}")

