
#
# These sources are part of the "PyThon Programming Series" by Edgar Milvus, 
# you can find it on Amazon: https://www.amazon.com/dp/B0FTTQNXKG or
# https://tinyurl.com/PythonProgrammingSeries 
# New books info: https://linktr.ee/edgarmilvus 
#
# MIT License
# Copyright (c) 2025 Edgar Milvus
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# Source File: basic_basic_code_example.py
# Description: Basic Code Example
# ==========================================

import os
from google import genai
from google.genai.types import GenerateContentConfig

# --- Configuration ---

# 1. Setup Client and Model
# The client automatically uses the GEMINI_API_KEY environment variable.
try:
    client = genai.Client()
except Exception as e:
    # Robust error handling for environment setup
    print(f"Error initializing client: {e}")
    print("CRITICAL: Please ensure the GEMINI_API_KEY environment variable is set correctly.")
    exit()

# gemini-2.5-flash is a supported and efficient model for grounding tasks.
model_id = "gemini-2.5-flash" 

# 2. Define the Target URLs
# These URLs are included directly in the prompt, allowing the model to retrieve them.
# NOTE: Use actual, publicly accessible URLs when running this script.
URL_A = "https://example.com/technical-deep-dive"
URL_B = "https://example.com/business-impact-report"

# 3. Define the Tool Configuration
# This dictionary structure is mandatory to activate the URL Context tool.
# It tells the model to use its internal web reader.
tools_config = [
    {"url_context": {}},
]

# 4. Construct the Prompt
# The prompt must clearly instruct the model what to do with the *provided* URLs.
prompt = (
    f"Analyze the content at the following two URLs: {URL_A} and {URL_B}. "
    "Provide a concise, two-paragraph summary comparing the main theoretical focus "
    "of URL A with the primary business application focus of URL B. "
    "Structure your response using markdown headers."
)

# --- Execution ---

print(f"-> Sending request to Gemini to analyze {URL_A} and {URL_B}...")
print("-" * 70)

try:
    # 5. Execute the API Call with Configuration
    response = client.models.generate_content(
        model=model_id,
        contents=prompt,
        config=GenerateContentConfig(
            tools=tools_config, # Injecting the URL Context tool here
        )
    )

    # 6. Display the Synthesized Results
    print("\n[ AI Synthesis Result ]")
    print("="*70)
    # The response text contains the comparison generated by the model
    print(response.text)
    print("="*70)

    # 7. Verification and Debugging Metadata
    # This metadata confirms that the tool was used and reports the retrieval status.
    print("\n[ URL Context Metadata for Verification ]")
    print(response.candidates[0].url_context_metadata)
    print("-" * 70)

except Exception as e:
    print(f"\nAn error occurred during content generation: {e}")
    print("Check connectivity, API key validity, and URL accessibility.")
